name: Deploy Docs
on: 
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install requirements
      run: |
        # Use the python executable provided by setup-python
        $(which python) -m pip install sphinx sphinx-rtd-theme
    - name: Verify Sphinx Installation
      run: |
        echo "Verifying Sphinx installation..."
        $(which python) -m pip show sphinx
        $(which python) -c "import sphinx; print(sphinx.__file__)"
    - name: Generate API docs
      run: |
        PYTHONPATH=$GITHUB_WORKSPACE $(which python) -m sphinx.apidoc -o docs/ dpnn_lib
    - name: Build documentation
      run: |
        sphinx-build -b html docs/ docs/_build/html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
